name: flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.2
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.2
  cached_network_image: 2.0.0-rc.1
  http: ^0.12.0+4
  simple_animations: ^1.2.0
  rounded_letter: ^0.0.6
  jiffy: ^2.2.0
  intl: ^0.16.0
  url_launcher: ^5.4.2
  loader_search_bar: ^1.0.3+3
  flutter_contact: ^0.4.7+10
  flutter_launcher_icons: "^0.7.3"
  permission_handler:
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_light.jpg"

flutter:
  assets:
    - assets/logo_dark.jpg
    - assets/logo_light.jpg

  uses-material-design: true
